# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 16:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('garanty', models.PositiveSmallIntegerField()),
                ('is_best_offer', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('value_mesure', models.PositiveSmallIntegerField()),
                ('measurer', models.CharField(choices=[('m', 'meters'), ('kg', 'kilograms'), ('p', 'pieces')], default='kg', max_length=2)),
                ('json', models.TextField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Brand')),
                ('from_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.ProductFrom')),
                ('image', models.ManyToManyField(to='catalogue.Image')),
                ('kind', models.ManyToManyField(to='catalogue.Kind')),
                ('special', models.ManyToManyField(to='catalogue.Special')),
            ],
        ),
    ]
