# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 16:02
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/images/brands')),
            ],
        ),
        migrations.CreateModel(
            name='BrandClothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=60)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/images/clothes')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.BrandClothe')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('extension', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png')], default='JPEG', max_length=4)),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/images/products')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('create_at', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('garanty', models.PositiveSmallIntegerField()),
                ('is_best_offer', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('value_mesure', models.PositiveSmallIntegerField()),
                ('measurer', models.CharField(choices=[('m', 'meters'), ('kg', 'kilograms'), ('p', 'pieces')], default='kg', max_length=2)),
                ('json', models.TextField()),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Category')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.ProductFrom'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(to='product.Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ManyToManyField(to='product.Kind'),
        ),
        migrations.AddField(
            model_name='product',
            name='special',
            field=models.ManyToManyField(to='product.Special'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.Size'),
        ),
    ]
