# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 13:33
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20160715_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_parameters_json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
