# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20160715_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(null=True, upload_to='go_fisher/static/go_fisher/img/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
