# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20160715_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(null=True, upload_to='go_fisher/static/go_fisher/img/brands'),
        ),
    ]
