# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20160715_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='special',
            field=models.ManyToManyField(null=True, to='product.Special'),
        ),
    ]
