# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20160716_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.Kind'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurer',
            field=models.CharField(choices=[('sm', 'см'), ('g', 'г'), ('p', 'шт')], default='g', max_length=2),
        ),
    ]
