# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20160716_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.ManyToManyField(to='product.Kind'),
        ),
    ]
