# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20160716_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.ManyToManyField(db_table='kind_prod', to='product.Kind'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measurer',
            field=models.CharField(choices=[('см', 'довжина'), ('гр', 'вага'), ('шт', 'кількість')], default='гр', max_length=2),
        ),
    ]
