# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20160717_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.ManyToManyField(to='product.Kind'),
        ),
    ]
