# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_params_json',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='images', to='product.Image'),
        ),
    ]
