# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-18 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20160918_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='measurer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value_mesure',
        ),
    ]
