# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/shop/images/brands')),
            ],
        ),
        migrations.CreateModel(
            name='BrandClothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('big_category', models.ManyToManyField(to='catalogue.BigCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField(max_length=60)),
                ('description', models.TextField()),
                ('active', models.BooleanField()),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/shop/images/clothes')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.BrandClothe')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('extension', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png')], default='JPEG', max_length=4)),
                ('image', models.FileField(null=True, upload_to='go_fisher/static/shop/images/products')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryBelong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bigcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.BigCategory')),
                ('subcategory_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Category')),
            ],
        ),
        migrations.AddField(
            model_name='productfrom',
            name='subcategory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Subcategory'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.Size'),
        ),
    ]
