# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20160707_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сategorybelong',
            name='bigcategory_id',
        ),
        migrations.RemoveField(
            model_name='сategorybelong',
            name='subcategory_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='big_category',
        ),
        migrations.AddField(
            model_name='category',
            name='big_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogue.BigCategory'),
        ),
        migrations.DeleteModel(
            name='СategoryBelong',
        ),
    ]
