# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160710_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FileField(null=True, upload_to='go_fisher/static/go_fisher/img/categories'),
        ),
    ]
