# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.FileField(null=True, upload_to='go_fisher/static/go_fisher/img/subcategories/'),
        ),
    ]
