# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160721_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='extra_parameters',
            field=models.TextField(null=True),
        ),
    ]
