# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('surename', models.CharField(max_length=45)),
                ('fathername', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=60)),
                ('city', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=45)),
                ('house_number', models.CharField(max_length=10)),
                ('hash_code', models.CharField(max_length=45)),
                ('datecreate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRestoredPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=60)),
                ('create_date', models.DateField(auto_now=True)),
                ('key', models.CharField(max_length=20)),
            ],
        ),
    ]
